import wsgiref.simple_server
import webapp2
from Handlers import *


############################# Main Functions ############################# 
def main (app):
    port = 8080
    httpd = wsgiref.simple_server.make_server('', port, app)
    print "Serving HTTP on port "+str(port)+"..."
    httpd.serve_forever()

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="From a gspec and a component library, compiles a schematic and semi-placed board.")
    parser.add_argument("-n", "--program_name", type=str,  default="testfile", help="The name of the program generated by the server")
    parser.add_argument("-e", "--program_ext", type=str, default="cpp", help="The file extention of the intermediary file generated by the server")
    parser.add_argument("-t", "--type", type=str, default="CppDefault.xml", help="The file extention of the intermediary file generated by the server")
    args = parser.parse_args()
    CompilationHandler = CompileInoHandler if args.program_ext == "ino" else CompileCPPHandler
    setupOutput( name=args.program_name, ext=args.program_ext, workspace=args.type)
    app = webapp2.WSGIApplication([ 
	("/", LandingHandler),
	("/newprogram", NewProgramHandler),
	("/killprogram", KillProgramHandler),
	(r'/programs/(.+)', ProgramHandler),
	(r'/static/(.+)', StaticFileHandler),
	("/compile", CompilationHandler),
	]    , debug=True)
    main(app)

